SITE = "https://junkjunkiesflorida.site"
PHONE_DISPLAY = "321-351-0284"
PHONE_TEL = "+13213510284"
EMAIL = "junkjunkiesflorida@gmail.com"
BRAND = "Junk Junkies Florida"

# slug, name, image, short blurb, long intro, what we take, how/price notes, faqs
SERVICES = [
 dict(slug="residential-junk-removal", name="Residential Junk Removal", img="residential",
  blurb="Whole-home haul-away. Point at it, we load it, you never lift a thing.",
  intro="Residential junk removal from Junk Junkies Florida is the fastest way to get unwanted items out of your house without renting a dumpster or making dump runs yourself. We send a crew to your home in Haines City or anywhere across Polk, Osceola and Orange counties, quote a flat price on the spot, and haul everything away the same visit.",
  takes=["Couches, chairs, tables and household furniture","Boxes, bags and general household clutter","Old electronics, TVs and small appliances","Closet, spare-room and attic cleanouts","Moving leftovers and downsizing piles","Exercise equipment, bikes and toys"],
  how="Pricing is based on how much space your items take up in our truck plus the labor to carry them out, so a few items costs far less than a full load. We load from wherever the items are — inside the house, garage, driveway or curb — and sweep up when we finish. Share a photo in the quote form and we can often confirm pricing before we arrive.",
  faqs=[("Do I need to be home during pickup?","Not always. If the items are accessible and we have confirmed the job and price, we can load without you being present. Most customers like to point things out at the start."),("Can you haul things from inside my home?","Yes. We carry items from any room, including upstairs, and protect doorways and floors as we go."),("How soon can you come?","We often have same-day and next-day availability around Haines City. Submit the quote form or call and tell us how soon you need it.")]),
 dict(slug="furniture-removal", name="Furniture Removal", img="furniture",
  blurb="Couches, sectionals, dressers, tables — out the door and off your property.",
  intro="Heavy, bulky furniture is the hardest junk to move on your own. Our furniture removal service in Haines City and Central Florida sends a crew that does all the lifting, navigates stairs and tight hallways, and loads straight into the truck so you are not left with a pile at the curb that the county will not pick up.",
  takes=["Sofas, sectionals, loveseats and recliners","Dressers, nightstands and bookcases","Dining tables, chairs and hutches","Desks, office chairs and filing cabinets","Patio and outdoor furniture","Entertainment centers and TV stands"],
  how="We price furniture by the space it fills in the truck, so one couch is a small, flat charge while a whole house of furniture is quoted as a larger load. We can disassemble oversized pieces when needed. If items are still usable we separate them from the load that goes to disposal whenever it is practical.",
  faqs=[("Can you remove furniture from upstairs or a tight space?","Yes. Our crew is used to stairs, narrow doorways and elevators and brings the tools to take pieces apart if they will not fit through."),("What happens to the furniture you take?","Usable items can be set aside for donation where practical; the rest is disposed of at the proper facility."),("Do you take just one item?","Yes. There is no minimum number of items, and a single piece is priced as a small load.")]),
 dict(slug="appliance-removal", name="Appliance Removal", img="appliances",
  blurb="Fridges, washers, dryers, stoves, AC units and water heaters.",
  intro="Old refrigerators, washers, dryers and stoves are heavy, awkward and often not accepted in regular trash pickup. Junk Junkies Florida provides appliance removal in Haines City and surrounding Polk County cities, with a crew that disconnects, carries and hauls appliances away so you do not have to risk your back or your floors.",
  takes=["Refrigerators and freezers","Washers and dryers","Stoves, ovens and ranges","Dishwashers and microwaves","Window and portable AC units","Water heaters and dehumidifiers"],
  how="Appliances are priced by the number of pieces and how much room they take in the truck. Bring an appliance outside if you like, or leave it where it sits and we will carry it out. Refrigerants and metal are handled so that appliances can be recycled where facilities accept them.",
  faqs=[("Can you take a fridge with food still inside?","Please empty it first. We can remove a refrigerator that is unplugged and cleared out."),("Do you disconnect appliances?","We can handle simple disconnects for removal. Gas lines and complex plumbing should be shut off by a licensed professional before we arrive."),("Are old appliances recycled?","Where recycling facilities accept them we route metal and appliances there rather than straight to a landfill.")]),
 dict(slug="mattress-removal", name="Mattress Removal", img="mattress",
  blurb="Any size mattress and box spring, hauled same day.",
  intro="Mattresses and box springs are bulky, hard to bag and often rejected by regular trash service. Our mattress removal service in Haines City and Central Florida is a quick, low-cost way to clear old beds out of bedrooms, garages and rental properties — we carry them out and take them away in one visit.",
  takes=["Twin, full, queen, king and California king mattresses","Box springs and foundations","Bed frames and headboards","Futons and daybeds","Memory foam and pillow-top toppers","Bunk beds and kids' beds"],
  how="Pricing is a simple per-piece charge for mattresses and box springs, and we can stack the removal with any other furniture or junk you want gone to save on the total. We wrap and carry pieces so nothing drags through your home.",
  faqs=[("Do you remove mattresses from apartments and rentals?","Yes. We regularly clear beds from rentals, vacation homes and apartment units for owners and property managers."),("Is there a bed bug concern?","Tell us if a mattress is infested so we can wrap it properly and keep it contained during removal."),("Can you take a bed frame too?","Absolutely. Frames, headboards and slats go in the same load.")]),
 dict(slug="garage-cleanouts", name="Garage Cleanouts", img="cleanout",
  blurb="Reclaim your garage. Floor-to-ceiling clutter, gone.",
  intro="Florida garages fill up fast — old paint cans, broken tools, boxes you never opened, and furniture with nowhere else to go. Our garage cleanout service in Haines City clears it all, so you can park the car again or finally use the space. We do the sorting, lifting and hauling.",
  takes=["Boxes, bins and stored household goods","Broken tools, shelving and workbenches","Old bikes, sports and exercise equipment","Scrap wood, metal and leftover materials","Lawn equipment and outdoor items","Furniture and appliances stored in the garage"],
  how="Garage cleanouts are priced by volume. Tell us what you want to keep and we will pull only what you point to, or take the whole contents. We sweep the floor when finished. Hazardous items like paint, chemicals and fuel are handled separately — mention them upfront.",
  faqs=[("Can you clear only part of the garage?","Yes. Point out what stays and what goes and we will load only the items you choose."),("Do you take paint and chemicals?","Hazardous liquids need special disposal. Let us know in advance and we will tell you what we can and cannot take."),("How long does a garage cleanout take?","Most single and double garages take a couple of hours depending on how full they are.")]),
 dict(slug="estate-cleanouts", name="Estate Cleanouts", img="estate",
  blurb="Respectful, organized full-property cleanouts for families and realtors.",
  intro="Clearing a loved one's home is hard enough without worrying about logistics. Our estate cleanout service in Haines City and Polk County provides a respectful, organized crew that works at your pace, sets aside items you want to keep, and removes everything else so the property is ready to list, rent or hand over.",
  takes=["Furniture, housewares and décor","Clothing, linens and personal items you choose to release","Garage, shed and attic contents","Appliances and electronics","Yard items and outdoor furniture","Remaining debris after family has taken what they want"],
  how="We walk the property, agree on what stays and what goes, and give a flat quote for the full cleanout. Items can be set aside for donation, and we leave the home broom-clean. We coordinate with realtors, attorneys and property managers on timing.",
  faqs=[("Can you work around a closing or listing date?","Yes. Tell us your deadline and we will schedule the cleanout to meet it."),("Will you set aside items we want to keep?","Yes. Mark or point out what stays and the crew will leave it untouched."),("Do you handle cleanouts for out-of-town families?","Yes. We can work from a walkthrough and photos and keep you updated until the property is clear.")]),
 dict(slug="hoarder-cleanup", name="Hoarder Cleanup", img="hoarder",
  blurb="Judgment-free, discreet crews. We sort, remove and sweep so the space is livable again.",
  intro="Hoarding situations call for patience, discretion and a crew that treats people with respect. Junk Junkies Florida provides judgment-free hoarder cleanout and cleanup in Haines City and Central Florida, working at a pace that suits you and the property, with gloves, masks and the manpower to handle heavy volume.",
  takes=["Heavy accumulations of household items","Bagged trash, papers and boxes","Damaged furniture and mattresses","Spoiled or unsanitary items (with proper protection)","Items blocking rooms, hallways and exits","Debris from multiple rooms, garages and sheds"],
  how="Every hoarding situation is different, so we start with a conversation and a walkthrough, then give a clear quote. Jobs may be done over several visits. We always set aside valuables, documents and sentimental items you identify. Our work is private — we do not share or discuss your situation.",
  faqs=[("Is the cleanup confidential?","Yes. We are discreet and respect the privacy of the people and families we work with."),("Can the work be done in stages?","Yes. Larger jobs can be split across visits to make the process manageable."),("Will you find and keep important items?","Our crew watches for documents, valuables and items of sentimental value and sets them aside for you.")]),
 dict(slug="storage-unit-cleanouts", name="Storage Unit Cleanouts", img="storage",
  blurb="We empty the unit so you can stop paying rent on junk.",
  intro="Monthly storage fees add up, especially when the unit holds things you no longer need. Our storage unit cleanout service meets you at the facility in Haines City, Davenport, Winter Haven, Lakeland and nearby areas, loads out everything you do not want, and lets you cancel the unit — no trips back and forth.",
  takes=["Furniture and household goods in storage","Boxes and totes of unwanted items","Old appliances and equipment","Business inventory and fixtures","Seasonal and holiday items","Anything left in an abandoned or inherited unit"],
  how="We coordinate gate access with you or the facility, then load out and haul everything to disposal, donation or recycling as appropriate. Pricing is based on the size of the unit and how full it is. We can do a full unit in a single visit in most cases.",
  faqs=[("Do I need to be present at the storage facility?","Usually we need access via your gate code or the facility manager. Many customers meet us briefly at the start."),("Can you clear a unit that is packed floor to ceiling?","Yes. Larger units are quoted as a bigger load, sometimes with a second truck trip."),("Will you leave the unit broom clean?","Yes, we sweep it out so it is ready to hand back.")]),
 dict(slug="yard-waste-removal", name="Yard Waste Removal", img="yard",
  blurb="Branches, palm fronds, brush, fencing and storm debris.",
  intro="Florida yards produce a lot of debris — fallen limbs, palm fronds, overgrown brush and storm damage. Our yard waste removal service in Haines City and Central Florida hauls it away so you are not waiting on slow county pickup or hauling it yourself, especially after a storm.",
  takes=["Tree limbs, branches and brush","Palm fronds and bagged yard clippings","Old fencing, lumber and pallets","Storm and hurricane debris","Landscape rock, pavers and soil piles (by volume)","Garden structures, planters and swing sets"],
  how="Yard debris is priced by the space it takes in the truck. We load directly from your yard or curb. For large tree work, tell us the size of the pile and we will quote the load. We can handle one-time cleanups and recurring seasonal clears.",
  faqs=[("Do you remove storm debris?","Yes. After storms we help clear limbs, fencing and damaged items from yards and driveways."),("Do you cut down trees?","We haul debris. We do not cut or remove standing trees, but we will take the limbs and logs once they are down."),("Do I need to bag the yard waste?","Not necessarily. We can load loose piles directly.")]),
 dict(slug="construction-debris-removal", name="Construction Debris Removal", img="construction",
  blurb="Drywall, lumber, tile, flooring and demo leftovers.",
  intro="Renovations leave behind a mess that standard trash service will not take. Our construction debris removal service helps homeowners, contractors and landlords in Haines City and Central Florida get rid of demo waste fast, with a crew that loads it for you so job sites stay clean and on schedule.",
  takes=["Drywall, plaster and insulation","Lumber, framing and trim","Tile, flooring and carpet","Cabinets, countertops and fixtures","Roofing scraps and siding","Concrete and brick pieces (by weight and volume)"],
  how="Construction debris is quoted by volume and weight. Contractors can schedule recurring pickups to keep a job site clear. Tell us what materials you have — heavy items like concrete, tile and shingles affect the load and the price.",
  faqs=[("Can you work with contractors on a schedule?","Yes. We can arrange recurring or on-call debris pickups for active job sites."),("Do you take concrete and tile?","Yes, in manageable quantities. Heavy materials are priced by weight and volume, so describe the amount when you request a quote."),("Do you remove asbestos or hazardous materials?","No. Hazardous materials such as asbestos require a licensed abatement company.")]),
 dict(slug="shed-removal", name="Shed Removal", img="shed",
  blurb="Teardown and haul-away of sheds, playsets and small structures.",
  intro="An old shed, rotted playset or sagging backyard structure takes up space and can be a safety hazard. Junk Junkies Florida provides shed removal and demolition in Haines City and surrounding cities — we take the structure apart, haul the debris, and leave the area ready for whatever comes next.",
  takes=["Wood, metal and plastic storage sheds","Playsets, swing sets and treehouses","Gazebos, pergolas and small decks","Chicken coops and dog houses","Contents left inside the structure","Fencing sections and lattice"],
  how="We price shed removal based on the structure's size, material and how much the contents add. Most sheds are taken down and hauled in a single visit. If there is a concrete slab, let us know in advance.",
  faqs=[("Do you remove what is inside the shed?","Yes. We can clear the contents and take down the structure in the same visit."),("Can you remove a shed with a concrete slab?","We can discuss slab removal as an add-on when you request a quote."),("How long does shed removal take?","Many small and medium sheds come down and are hauled within a few hours.")]),
 dict(slug="hot-tub-removal", name="Hot Tub Removal", img="hottub",
  blurb="Hot tubs and spas disconnected, cut up and carried out.",
  intro="A broken or unused hot tub is heavy, awkward and takes real equipment to move. Our hot tub removal service in Haines City and Central Florida includes cutting up and carrying out the spa, so your deck, patio or yard is clear without you needing to rent tools or call multiple companies.",
  takes=["Acrylic and portable hot tubs","In-ground and above-ground spas","Swim spas (call for details)","Hot tub covers, steps and equipment","Decks and platforms the tub sat on","Related pumps and equipment"],
  how="Have the tub drained and the power disconnected by a qualified electrician before we arrive. We then cut, carry and haul away the shell and equipment. Pricing depends on the size and access to the tub.",
  faqs=[("Do I need to drain the hot tub first?","Yes. Please drain it and have the power safely disconnected before our visit."),("Can you remove a built-in hot tub?","Often yes. Describe the setup when you request a quote and we will advise."),("Will you remove the deck underneath?","We can include deck or platform removal in the quote when needed.")]),
 dict(slug="commercial-junk-removal", name="Commercial Junk Removal", img="commercial",
  blurb="Offices, retail, warehouses and job sites — on your schedule.",
  intro="Businesses cannot afford downtime. Our commercial junk removal service in Haines City and Central Florida works around your hours to clear old furniture, fixtures, equipment and debris from offices, retail spaces, warehouses, restaurants and rental units — fast, clean, and with a flat quote.",
  takes=["Office furniture, cubicles and desks","Retail fixtures, shelving and displays","Restaurant and kitchen equipment","Warehouse pallets and surplus","Tenant move-out leftovers","Renovation and build-out debris"],
  how="We schedule commercial cleanouts evenings, weekends or off-hours when needed. Property managers and contractors can set up recurring or on-call service. We provide a clear written quote and keep the area tidy while we work.",
  faqs=[("Can you work after hours?","Yes. We can schedule evening and weekend pickups to avoid disrupting your business."),("Do you serve property managers?","Yes. We help property managers with tenant move-outs, unit turnovers and recurring cleanouts."),("Can you provide a written quote?","Yes. Send us details through the quote form and we will confirm pricing before we start.")]),
 dict(slug="property-cleanouts", name="Property Cleanouts", img="property",
  blurb="Vacant homes, rentals, foreclosures and move-outs cleared top to bottom.",
  intro="Vacant properties, rentals, foreclosures and move-outs often come with whatever the last occupant left behind. Our property cleanout service in Haines City and Central Florida clears the entire property — inside, garage, shed and yard — so investors, landlords, realtors and owners can turn it over quickly.",
  takes=["Furniture, appliances and household items left behind","Trash, debris and abandoned belongings","Garage, shed and yard clutter","Carpet, flooring and fixtures slated for removal","Items from multiple rooms and levels","Post-eviction and post-foreclosure cleanouts"],
  how="We give a flat quote for the whole property after a walkthrough or photos, then clear it in one scheduled visit where possible. We work with realtors, investors and property managers who need fast turnaround, and we leave the property broom-clean.",
  faqs=[("How fast can you clear a vacant property?","Most properties can be scheduled quickly, and many are done in a single day. Tell us your deadline."),("Do you work with investors and realtors?","Yes. We regularly handle cleanouts for investors, landlords and listing agents who need quick turnover."),("Do you clear the yard and shed too?","Yes. We can clear the whole property — interior, garage, shed and yard.")]),
]

CITIES = [
 dict(slug="haines-city", name="Haines City", county="Polk County", hq=True,
  intro="Junk Junkies Florida is based right here in Haines City, so we are the local junk removal crew for homes and businesses along US-27, near Lake Eva and in the neighborhoods around town. Being headquartered at 180 Dyson Rd means fast scheduling, same-day availability on many jobs, and no long travel time to your door.",
  local="Haines City sits in the heart of Polk County between Orlando and Lakeland, with a mix of established neighborhoods, newer subdivisions and a growing number of rental and investment properties. We clear everything from a single couch to a full garage, estate or rental turnover.",
  nearby=["Davenport","Auburndale","Winter Haven","Poinciana"]),
 dict(slug="davenport", name="Davenport", county="Polk County",
  intro="We provide junk removal in Davenport, FL for homeowners, landlords and vacation-rental owners. Davenport's fast-growing communities near I-4 and US-27 generate a steady stream of move-outs, renovations and furniture swaps, and our crew handles them with flat, upfront pricing.",
  local="With many newer homes, townhomes and vacation rentals in and around Davenport, we frequently handle furniture removal, appliance replacement hauls, property cleanouts between guests or tenants, and construction leftovers from renovations.",
  nearby=["Haines City","Kissimmee","Poinciana","Orlando"]),
 dict(slug="winter-haven", name="Winter Haven", county="Polk County",
  intro="Need junk removal in Winter Haven? Junk Junkies Florida serves homes and businesses throughout the Winter Haven area, from lakefront properties on the Chain of Lakes to neighborhoods and commercial spaces across town. We haul furniture, appliances, yard debris and full cleanouts quickly and cleanly.",
  local="Winter Haven's lakes, older homes and active residential market mean lots of cleanouts, storm debris cleanup, shed and dock-side leftovers, and estate clearing. We bring the crew and the truck; you decide what goes.",
  nearby=["Auburndale","Haines City","Lakeland","Davenport"]),
 dict(slug="lakeland", name="Lakeland", county="Polk County",
  intro="Junk Junkies Florida offers junk removal in Lakeland, FL for homes, rentals and businesses. As Polk County's largest city, Lakeland has everything from historic neighborhoods to new developments and commercial corridors, and we handle jobs of every size across all of them.",
  local="Whether you are clearing an estate near downtown, turning over a rental, or emptying a garage or storage unit, our Lakeland junk removal service provides flat pricing, a crew that does all the lifting, and responsible disposal.",
  nearby=["Auburndale","Winter Haven","Haines City","Tampa"]),
 dict(slug="kissimmee", name="Kissimmee", county="Osceola County",
  intro="We serve Kissimmee with fast, reliable junk removal for homeowners, landlords and vacation-rental managers. Kissimmee's many rental homes and tourist-area properties mean frequent turnovers, furniture replacements and cleanouts, and Junk Junkies Florida is ready to clear them on your schedule.",
  local="From vacation homes near the theme parks to neighborhoods around Lake Tohopekaliga, we remove furniture, mattresses, appliances and leftover guest or tenant belongings and can work around check-in and check-out dates.",
  nearby=["Poinciana","Davenport","Orlando","Haines City"]),
 dict(slug="poinciana", name="Poinciana", county="Polk and Osceola Counties",
  intro="Junk Junkies Florida provides junk removal in Poinciana, a large residential community straddling the Polk and Osceola county line. Many Poinciana homes are single-family houses with garages and yards, which means regular demand for garage cleanouts, furniture removal and yard debris hauling.",
  local="We help Poinciana homeowners, investors and landlords with move-outs, property cleanouts, mattress and appliance removal and storm debris — all with an upfront quote and no heavy lifting on your part.",
  nearby=["Kissimmee","Davenport","Haines City","Orlando"]),
 dict(slug="auburndale", name="Auburndale", county="Polk County",
  intro="Looking for junk removal in Auburndale? Junk Junkies Florida serves Auburndale and the area between Lakeland and Winter Haven with fast, affordable hauling of furniture, appliances, yard waste and full property cleanouts.",
  local="Auburndale's mix of lakeside homes, family neighborhoods and rural lots produces plenty of yard debris, shed teardowns and garage cleanouts. Our crew loads from wherever the items are and leaves your property clean.",
  nearby=["Lakeland","Winter Haven","Haines City","Tampa"]),
 dict(slug="orlando", name="Orlando", county="Orange County",
  intro="Junk Junkies Florida travels to Orlando for junk removal jobs of all sizes. While we are headquartered in Haines City, we schedule Orlando and nearby area cleanouts, estate clearing, property turnovers and commercial hauling by appointment.",
  local="For larger Orlando jobs — whole-house cleanouts, rental turnovers, storage units and commercial spaces — we plan the visit in advance, quote it flat, and bring the crew and truck to clear it in a single trip when possible.",
  nearby=["Kissimmee","Davenport","Poinciana","Haines City"]),
 dict(slug="tampa", name="Tampa", county="Hillsborough County",
  intro="We serve the Tampa area with junk removal for larger and scheduled jobs. From our Haines City base we travel to Tampa for estate cleanouts, property and rental turnovers, commercial cleanouts and construction debris removal.",
  local="Because Tampa is further from our home base, we schedule Tampa jobs by appointment and quote them upfront. Tell us what you need cleared and when, and we will confirm availability and a flat price.",
  nearby=["Lakeland","Auburndale","Winter Haven","Haines City"]),
]
